### ISSUE TITLE
'generate_masks' is not an option for training

### ISSUE THREAD

**Issue by NakitaOza** [jnyborg/fcd#1]
Hi! I read your paper and found it very interesting! . I am pursuing my master thesis in the field of cloud detection.
I am trying to setup the code here and following the steps you have mentioned.
I have run the second step :
`python fcd_main.py --mode train --dataset L8Biome --image_size 128 --batch_size 16 --experiment_name FCD`

Now, I want to move to the next step:
`python fcd_main.py --mode generate_masks --batch_size 64 --experiment_name FCD`

When the run this command, The get the below error:
> fcd_main.py: error: argument --mode: invalid choice: 'generate_masks' (choose from 'train', 'test', 'visualize')

I could not find `generate_masks` anywhere in the code base except for the Readme. 
Please let me know how to proceed.

**Comment by NakitaOza** [comment]
Found it in prepare_landasat8_biome.py

**Comment by jnyborg** [comment]
Hi! Glad to hear you found it interesting! It would seem that mode does not exist anymore, I must have changed it at some point. Instead you should run `--mode test`:

This will trigger here:
https://github.com/jnyborg/fcd/blob/main/fcd_main.py#L38

To run `make_pseudo_masks` here:
https://github.com/jnyborg/fcd/blob/main/fcd_solver.py#L577

I'll update the readme with the correct argument.

**Comment by NakitaOza** [comment]
Perfect! Thanks for the response!
